
# SEO settings
title: "TONY"
title2: "SOFT" # default: ""
description: "Internet is my bestfriend..."
keywords: "Web Development, Software Engineering, Life, Self-Thoughts"
url: https://iamtonysoft.github.io/blog # site url
baseurl: "/blog" # apply repo name if use it under gh-pages branch
                 # baseurl: null # apply null if repo name is something like username.github.io

# comment setting (disqus)
disqus_shortname: "iamtonysoft"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Anthony L. Cortez"
  job      : "Software Engineer / Information Systems Specialist"
  thumb    : /assets/images/author.jpg
  email    : iamtonysoft@gmail.com
  url      : https://iamtonysoft.github.io
  github   : https://github.com/iamtonysoft
  twitter  : 
  facebook : https://www.facebook.com/tonytheinternetsownboy
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: ""
twitter_username: ""

plugins:
  - bourbon
  - jekyll-paginate
  - jekyll-watch

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
